version: '3.8'

services:
  dashboard:
    build:
      context: .
      target: dashboard
      args:
        - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
        - NEXT_PUBLIC_SELF_HOSTED=${NEXT_PUBLIC_SELF_HOSTED}
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_RESERVED_SUBDOMAINS=${NEXT_PUBLIC_RESERVED_SUBDOMAINS}
      - NEXT_PUBLIC_REDIRECTION_URL=${NEXT_PUBLIC_REDIRECTION_URL}
    env_file: .env
    restart: always
